### ISSUE TITLE
EVReflection parse to array issue Swift 2.0?

### ISSUE THREAD

**Issue by tobiasolofssonevry** [evermeer/EVReflection#22]
In my podfile:`
use_frameworks!
pod 'EVReflection', '~> 2.6'`

Added a class:

```
public class SubscriptionsItem: EVObject {
    var subscriptionId: String = ""
    var title: String = ""
    var count: Int = 0
}
```

Now i'm trying to parse json data to my array of SubscriptionsItems:
`subscriptionEntries = [SubscriptionsItem](json: responseObject)`

I'm getting `'Cannot invoke initiallizer for type '[SubscriptionsItem]' with an argument list of type '(json: String)'.`

Can't figure out what i'm doing wrong here?

**Comment by evermeer** [comment]
I think you turned the versioning around.
You should use EVReflection version 2.6 if you want to use it with Swift 1.2
If you want to use EVRelfection with Swift 2, then you can just use the latest version like this:

use_frameworks! 
pod 'EVReflection'

**Comment by tobiasolofssonevry** [comment]
That fixed my issue, sorry for mixing up the versions. Solved

**Comment by tobiasolofssonevry** [comment]
However i'm getting an error after using the latest version now.

setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key owner.'

![skarmavbild 2015-10-05 kl 14 13 05](https://cloud.githubusercontent.com/assets/6933891/10280154/5befd0ee-6b6b-11e5-9245-9954b42c1f93.png)

Valid JSON that has been working in previous versions now giving this.

Any idea?

**Comment by evermeer** [comment]
All NSObject and EVObject classes have a default implementation for setValue forUndefinedKey. Whenever there is an unknown key you will only get a log line in your output window. 

Your screenshot indicates that it's on line 542 in EVReflection. When you do hit that breakpoint, then what type of object is the anyObject on that line? The setObjectValue function ensures that it should be of type NSObject and NSObject is extended with the setValue forUndefinedKey. so I wonder war's going on.   It should not break. You should get a warning in your output window.

**Comment by ostatnicky** [comment]
This

```
use_frameworks! 
pod 'EVReflection'
```

doesn't solve problem with Swift 2. (Xcode 7.0.1)

**Comment by evermeer** [comment]
@ostatnicky Is that a new problem? I can't place your comment in this thread. Maybe it should have been a new issue? When you have that in your pod and do a 'pod update' you should see that version 2.9.3 is downloaded. To be sure do a clean build and remove your derived data.

@tobiasolofssonevry If you still have a problem, Then It would be very helpful if you could give me the json you use plus the object definition(s) that you are creating from it. It's very hard to tell what's going wrong from what you describe above.

**Comment by ostatnicky** [comment]
Yes, I had 2.9.3, after update I've got 2.10.0 but still I got that error.

**Comment by evermeer** [comment]
@ostatnicky  2.10.0 is OK. I pushed a new version yesterday with new functionality.

So you say that you have a similar problem as tobias had? An error similar to: 
setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key owner.'
If so, could you please create a new issue with a little more details? 

Ideally I would like  to see the json and the object that you defined for it so that I can create a unit test for it to see where it fails.

**Comment by anansi** [comment]
Hi @evermeer 

Im having the same issue as @ostatnicky where i have updated to the latest version (2.11.1) but i still get 
class User: EVObject {
        var id: Int = 0
        var name: String = ""
}

'Cannot invoke initiallizer for type '[User]' with an argument list of type '(json: String)'
On the line:  
let users = [User](json: userString)

Please advise?

**Comment by evermeer** [comment]
@anansi I guess that you mean that you get a compile error on a statement like this:
   let users = [User](json: jsonString)
When you download the latest version (currently indeed 2.11.1) then you can see a unit test for that construction at line 66 of testJsonObject.swift

If you want to check if you have got the correct version in your code, then go to the file EVExtensions.swift in your pods folder. On line 95 you should see : 
    extension Array 
with on line 104 an 
   init(json:String? {

**Comment by ianzitow** [comment]
I'm facing this problem: "Argument labels '(json:)' do not match any available overloads", what should I do?

**Comment by evermeer** [comment]
@ianzitow It looks like you don't have EVReflection available in your app. Did you add it using cocoapods? Did it download the latest version (currently 2.12.0)? Did you open the workspace instead of the project? In Xcode you should also see a Pods project. And in that project you should have a Pods folder that contains an EVReflection folder. In that EVReflection folder you should see 4 swift files. The overload with the init with json can be found in EVExtensions.swift. Can you see that file?

**Comment by ianzitow** [comment]
Yea, I did everything. I could import it to my projects and create subclasses of EVObjects, then it was being recognized in my workspace. However, the overload for "json" was not available. So, I decided to download the 4 swift files and add them manually after removing from CocoaPods and it worked! Looks like "EVExtensions.swift" is not being loaded by Xcode.

**Comment by evermeer** [comment]
@ianzitow Did you have an import EVReflection above your class definition?

**Comment by ianzitow** [comment]
Yes, only the extension for arrays is not working.

**Comment by ApplicationNinja** [comment]
To fix: "Argument labels '(json:)' do not match any available overloads"

Line #95 of EVExtensions.swift needs to be: public extension Array

"public" was left off.

**Comment by evermeer** [comment]
@TechnologySolutionsGroup Thanks for catching that!

@ianzitow I just pushed a new version to GitHub with the fix.

**Comment by ianzitow** [comment]
Thank you @evermeer and congratulations for the project!

**Comment by quentinfasquel** [comment]
I believe my issue might be related.. I just use the example:

```
import EVReflection

class User: EVObject {
    var id: Int = 0
    var name: String = ""
    var friends: [User]? = []
}

let json:String = "{\"id\": 24, \"name\": \"Bob Jefferson\", \"friends\": [{\"id\": 29, \"name\": \"Jen Jackson\"}]}"
let user = User(json: json)
print(user)
```

Result :

```
User {
   hash = 2985078112003787766
   key = id, value = 24
   key = name, value = Bob Jefferson
   key = friends, value = (
)
}
```

As you can see in the result, the array parsing didn't work... How do I get this to work?
Thank you in advance for your answers!

**Comment by evermeer** [comment]
I can have a look at this tomorow. I reopened this issue so that i don't loose track.

**Comment by quentinfasquel** [comment]
Ok, I have investigated a bit and it seems I found the issue, and two things:
1- There is a workaround.
2- It isn't really an issue unless you expect a full handling of Swift possibilities.

It appears that EVReflection's `swiftClassTypeFromString` expect "appName.className" to be the Swift class type. But two things:
1- Swift can have nested classes. That was my main issue.
2- In a very specific case, I was declaring a class in a unit test file (just temporary for debugging, I agree this isn't something people do), therefore User wasn't MyAppName.User but something different.

@evermeer I would suggest to solve the nested class case, I don't know about the unit test situation I "created"... but I would also consider taking a look at how Playground would work, even though I haven't been able to import a custom framework into Playgroud.

**Comment by evermeer** [comment]
When you are using EVReflection with objects in a different framework/bundle/app, then you have to tell EVReflection that it should use that bundle by calling something like:
`EVReflection.setBundleIdentifier(TestObject)`
Sub objects are also handled. In that case the original identifier will be used instead of the dot notation. 
You can find the unit tests for that here:
https://github.com/evermeer/EVReflection/blob/9f71805c920c39edab567ab775ae2fafc3d731a3/EVReflection/EVReflectionTests/EVReflectionNestedObjectsTests.swift#L36-36
and: https://github.com/evermeer/EVReflection/blob/a7cf834453ee19ebbc45dbc473a413918dc6f1ce/EVReflection/EVReflectionTests/EVReflectionTests.swift#L227-227

**Comment by quentinfasquel** [comment]
@evermeer Thank you.
Although I do not see any nested class in the unit tests.

```
class A: EVObject {
    class B: EVObject {
        var id: String = ""
    }

    var id: String = ""
    var nestedClassProperty: A.B?
}

let json = "{\"id\":\"anObjectOfClassA\", \"nestedClassProperty\": {\"id\": \"aSubObjectOfClassB\"}}"
let a = A(json: json)
print(a)
```

This doesn't work as you can notice with the result. (Unless there is something I haven't figure out) :

```
A {
   hash = 6734422897927018510
   key = id, value = anObjectOfClassA
   key = nestedClassProperty, value = <null>
}
```

**Comment by evermeer** [comment]
Ah, sorry, you meant nested objects in the class definition. I thought you meant usage.

I did do some tests with nested declaration, but apparently not enough.
https://github.com/evermeer/EVReflection/blob/5b09a17b61459b37281f3de26442ebb56b5f177e/EVReflection/EVReflectionTests/EVObjectDescriptionTests.swift#L37-37
I will do some more investigation to see how I can fix this.

**Comment by evermeer** [comment]
Ah, I see where it goes wrong. 
When the sub object is declared as an optional, then there is a problem with getting the specific type.
When you replace the nestedClassProperty with the following line then it works:
    var nestedClassProperty: Inner = Inner()
I will have a look to see If I can also make this work with optionals.

**Comment by evermeer** [comment]
I finally succeeded in solving the issue of optional nested objects with inner class definitions. This is now published as version 2.18.1
